package com.consltApp.spring.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "movies")
public class Movie {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long movieid;
  
  // The movie's title.
  @NotNull
  private String title;
  
  // The user's name
  @NotNull
  private int genreid;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Movie() { }

  public Movie(long id) { 
    this.movieid = id;
  }
  
  public Movie(String title, int genreid) {
    this.title = title;
    this.genreid = genreid;
  }

  // Getter and setter methods

  public long getMovieid() {
    return movieid;
  }

  public void setMovieid(long value) {
    this.movieid = value;
  }

  public String getTitle() {
    return title;
  }
  
  public void setTitle(String title) {
    this.title = title;
  }
  
  public int getGenreid() {
    return genreid;
  }

  public void setGenreid(int value) {
    this.genreid = value;
  }
  
} // class movie
